services:
  spark:
    image: apache/spark:3.5.0
    container_name: spark-local
    ports:
      - "4040:4040"   # interface web Spark
      - "7077:7077"   # port ma√Ætre Spark

    command: /bin/bash