services:
  spark:
    image: apache/spark:3.5.0
    container_name: spark-local
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    ports:
      - "4040:4040"   # UI Spark
      - "7077:7077"   # Port Spark master (si besoin)