version: "3.8"

services:
  spark:
    volumes:
      - C:\Users\Pc\les tp de java\Projet_Java_QoS-QoE:/app
      - C:\Users\Pc\les tp de java\Projet_Java_QoS-QoE\src\main\resources\data:/data
    stdin_open: true
    tty: true
    command: /bin/bash
